variable "task_file_name" {}
variable "container_name" {}
variable "app_image" {}
variable "container_cpu" {}
variable "container_memory" {}
variable "container_port" {}
variable "aws_region" {}
variable "env_var_1" {}
variable "env_var_2" {}
variable "env_var_3" {}
variable "env_var_4" {}
variable "env_var_5" {}
variable "docker_hub_arn" {}
variable "vpc_id" {}
variable "health_check_path" {}
variable "listener_arn" {}
variable "service_path" {}
variable "ecs_task_execution_role_arn" {}
variable "task_definition_role_arn" {}
variable "cluster_name" {}
variable "app_count" {}